export const STYLES = `
:root{color-scheme:dark;font-family:var(--xsec-font-family,Inter,"Segoe UI",system-ui,sans-serif);--ct-bg:var(--xsec-content-surface,#0c1018);--ct-panel:var(--xsec-bg-subtle,#111722);--ct-card:var(--xsec-content-surface,#151c28);--ct-card-user:color-mix(in srgb,var(--ct-card) 90%,var(--ct-accent-soft));--ct-text:var(--xsec-text-primary,#d6deeb);--ct-secondary:var(--xsec-text-secondary,#a7b0c0);--ct-tertiary:var(--xsec-text-tertiary,#7f899c);--ct-border:var(--xsec-border-default,#293144);--ct-border-strong:var(--xsec-border-strong,#52617d);--ct-accent:var(--xsec-accent,#5b74ff);--ct-accent-soft:var(--xsec-accent-soft,rgba(91,116,255,.16));--ct-error:var(--xsec-status-error,#ff8f8f);--ct-error-soft:var(--xsec-status-error-subtle,rgba(240,87,87,.13));--ct-warning:var(--xsec-status-warning,#f0b959);--ct-success:var(--xsec-status-success,#69ddb7);--ct-shadow:var(--xsec-shadow-md,0 8px 20px rgba(0,0,0,.2))}
:root[data-xsec-theme="light"]{color-scheme:light;--ct-bg:var(--xsec-content-surface,#fff);--ct-panel:var(--xsec-bg-subtle,#f5f7fa);--ct-card:var(--xsec-content-surface,#fff);--ct-text:var(--xsec-text-primary,#202737);--ct-secondary:var(--xsec-text-secondary,#4f5a6d);--ct-tertiary:var(--xsec-text-tertiary,#7c8799);--ct-border:var(--xsec-border-default,#dce1ea);--ct-border-strong:var(--xsec-border-strong,#aeb7c7);--ct-shadow:var(--xsec-shadow-md,0 7px 18px rgba(32,39,55,.12))}
*{box-sizing:border-box}html,body,[data-xsec-plugin-root]{width:100%;height:100%;margin:0}body{overflow:hidden;background:var(--ct-bg);color:var(--ct-text)}button,input{font:inherit}.ct-root{display:flex;width:100%;height:100%;min-width:0;flex-direction:column;overflow:auto;padding:12px;gap:10px;background:var(--ct-bg);color:var(--ct-text)}
.ct-toolbar{display:grid;min-width:0;grid-template-columns:minmax(0,1fr) auto auto;align-items:center;gap:8px}.ct-title{display:grid;min-width:0;gap:1px}.ct-title strong{overflow:hidden;font-size:14px;text-overflow:ellipsis;white-space:nowrap}.ct-title small,.ct-summary{color:var(--ct-tertiary);font-size:10.5px}.ct-badge{display:inline-flex;height:24px;align-items:center;padding:0 8px;border:1px solid var(--ct-border);border-radius:999px;background:var(--ct-panel);color:var(--ct-secondary);font-size:10px;white-space:nowrap}.ct-badge.is-ready,.ct-badge.is-cached{color:var(--ct-success)}.ct-badge.is-error{color:var(--ct-error)}.ct-icon-button,.ct-action{display:inline-flex;min-height:30px;align-items:center;justify-content:center;border:1px solid var(--ct-border);border-radius:7px;background:var(--ct-card);color:var(--ct-secondary);cursor:pointer}.ct-icon-button{width:30px;padding:0;font-size:15px}.ct-action{padding:5px 10px;font-size:11px}.ct-icon-button:hover:not(:disabled),.ct-action:hover:not(:disabled),.ct-icon-button:focus-visible,.ct-action:focus-visible{border-color:var(--ct-accent);outline:2px solid var(--ct-accent-soft);outline-offset:1px;color:var(--ct-text)}button:disabled{cursor:not-allowed;opacity:.45}
.ct-filters{display:grid;min-width:0;grid-template-columns:minmax(0,1fr) auto;gap:8px}.ct-search{width:100%;height:32px;padding:0 10px;border:1px solid var(--ct-border);border-radius:7px;outline:none;background:var(--ct-panel);color:var(--ct-text);font-size:11.5px}.ct-search:focus{border-color:var(--ct-accent);box-shadow:0 0 0 2px var(--ct-accent-soft)}.ct-segments{display:flex;padding:2px;border:1px solid var(--ct-border);border-radius:7px;background:var(--ct-panel)}.ct-segments button{min-width:58px;padding:3px 8px;border:0;border-radius:5px;background:transparent;color:var(--ct-secondary);cursor:pointer;font-size:11px}.ct-segments button[aria-pressed="true"]{background:var(--ct-card);box-shadow:var(--ct-shadow);color:var(--ct-text)}.ct-role-filter{display:flex;width:max-content;align-items:center;gap:7px;color:var(--ct-secondary);font-size:11px;cursor:pointer}.ct-role-filter input{accent-color:var(--ct-accent)}
.ct-notice{padding:8px 10px;border:1px solid color-mix(in srgb,var(--ct-warning) 35%,transparent);border-radius:7px;background:color-mix(in srgb,var(--ct-warning) 10%,transparent);color:var(--ct-warning);font-size:11px;line-height:1.5;overflow-wrap:anywhere}.ct-notice.is-error{border-color:color-mix(in srgb,var(--ct-error) 35%,transparent);background:var(--ct-error-soft);color:var(--ct-error)}.ct-notice[hidden]{display:none}.ct-empty{display:grid;min-height:220px;place-content:center;justify-items:center;gap:9px;padding:26px;border:1px dashed var(--ct-border);border-radius:9px;background:var(--ct-panel);text-align:center}.ct-empty strong{font-size:13px}.ct-empty span{max-width:320px;color:var(--ct-tertiary);font-size:11px;line-height:1.55}.ct-empty[hidden]{display:none}
.ct-canvas{position:relative;width:100%;height:clamp(220px,48vh,520px);min-height:220px;flex:0 0 auto;overflow:hidden;overscroll-behavior:contain;border:1px solid var(--ct-border);border-radius:9px;outline:none;background-color:var(--ct-panel);background-image:radial-gradient(circle,color-mix(in srgb,var(--ct-tertiary) 22%,transparent) 1px,transparent 1px);background-size:16px 16px;cursor:grab;touch-action:none;user-select:none}.ct-canvas[hidden]{display:none}.ct-canvas.is-dragging{cursor:grabbing}.ct-stage{position:absolute;top:0;left:0;transform-origin:0 0;will-change:transform}.ct-links{position:absolute;inset:0;overflow:visible;pointer-events:none}.ct-links path{fill:none;stroke:var(--ct-border-strong);stroke-linecap:round;stroke-width:1.5;vector-effect:non-scaling-stroke}.ct-links path.is-active{stroke:var(--ct-accent);stroke-width:2}
.ct-node{position:absolute;top:0;left:0;display:grid;width:166px;height:66px;grid-template-rows:16px minmax(0,1fr) 14px;gap:1px;overflow:hidden;padding:7px 9px;border:1px solid var(--ct-border);border-radius:8px;background:var(--ct-card);box-shadow:var(--ct-shadow);color:var(--ct-secondary);cursor:pointer;text-align:left;transform-origin:0 0;transition:border-color 120ms ease,box-shadow 120ms ease,opacity 120ms ease}.ct-node.role-user{background:var(--ct-card-user)}.ct-node:hover,.ct-node:focus-visible{border-color:var(--ct-accent);outline:2px solid var(--ct-accent-soft);outline-offset:1px}.ct-node.is-active{border-color:color-mix(in srgb,var(--ct-accent) 58%,var(--ct-border))}.ct-node.is-selected{border-color:var(--ct-accent);box-shadow:0 0 0 2px var(--ct-accent-soft),var(--ct-shadow)}.ct-node.is-dimmed{opacity:.24}.ct-node-meta{display:flex;align-items:center;justify-content:space-between;color:var(--ct-tertiary);font-size:9.5px;line-height:14px}.ct-node-meta i{padding:0 5px;border-radius:999px;background:var(--ct-accent-soft);color:var(--ct-accent);font-style:normal}.ct-node strong{overflow:hidden;color:var(--ct-text);font-size:11px;line-height:15px;text-overflow:ellipsis;white-space:nowrap}.ct-node small{color:var(--ct-tertiary);font-size:9.5px;line-height:13px}
.ct-zoom{position:absolute;z-index:2;right:8px;bottom:8px;display:flex;align-items:center;gap:2px;padding:3px;border:1px solid var(--ct-border);border-radius:8px;background:color-mix(in srgb,var(--ct-card) 92%,transparent);box-shadow:var(--ct-shadow);touch-action:manipulation}.ct-zoom button{min-width:30px;height:30px;padding:0 6px;border:0;border-radius:5px;background:transparent;color:var(--ct-secondary);cursor:pointer}.ct-zoom button:hover:not(:disabled),.ct-zoom button:focus-visible{background:var(--ct-accent-soft);outline:none;color:var(--ct-text)}
.ct-inspector{display:grid;min-width:0;gap:10px;padding:12px;border:1px solid var(--ct-border);border-radius:9px;background:var(--ct-panel)}.ct-inspector[hidden]{display:none}.ct-inspector header{display:flex;min-width:0;align-items:center;justify-content:space-between;gap:8px}.ct-tags{display:flex;min-width:0;flex-wrap:wrap;gap:4px}.ct-tag{display:inline-flex;min-height:21px;align-items:center;padding:2px 7px;border-radius:999px;background:var(--ct-card);color:var(--ct-secondary);font-size:10px}.ct-tag.is-current{background:var(--ct-accent-soft);color:var(--ct-accent)}.ct-preview{max-height:8em;margin:0;overflow:auto;color:var(--ct-secondary);font-size:12px;line-height:1.6;overflow-wrap:anywhere;white-space:pre-wrap}.ct-facts,.ct-context dl{display:grid;min-width:0;grid-template-columns:74px minmax(0,1fr);gap:6px 10px;margin:0}.ct-facts dt,.ct-context dt{color:var(--ct-tertiary);font-size:10.5px}.ct-facts dd,.ct-context dd{min-width:0;margin:0;overflow:hidden;color:var(--ct-secondary);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.ct-context-toggle{display:flex;width:100%;align-items:center;gap:6px;padding:8px 0 0;border:0;border-top:1px solid var(--ct-border);background:transparent;color:var(--ct-secondary);cursor:pointer;font-size:11px;font-weight:600;text-align:left}.ct-context-toggle:focus-visible{outline:2px solid var(--ct-accent-soft);outline-offset:2px}.ct-context{display:grid;min-width:0;gap:9px;padding:10px;border-radius:7px;background:var(--ct-card)}.ct-pills{display:flex;min-width:0;flex-wrap:wrap;align-items:center;gap:4px}.ct-pills strong{margin-right:4px;color:var(--ct-secondary);font-size:10.5px}.ct-context-note{color:var(--ct-tertiary);font-size:10px;line-height:1.5}.ct-context[hidden]{display:none}
@media(max-width:360px){.ct-root{padding:9px}.ct-filters{grid-template-columns:1fr}.ct-segments button{flex:1}.ct-toolbar{grid-template-columns:minmax(0,1fr) auto auto}.ct-inspector header{align-items:flex-start;flex-direction:column}.ct-action{width:100%}}
@media(max-height:420px){.ct-root{padding:8px}.ct-canvas{height:220px}.ct-title small{display:none}}
@media(prefers-reduced-motion:reduce){.ct-node{transition:none}.ct-stage{will-change:auto}}
`;

export function installStyles() {
  if (document.getElementById("xsec-conversation-tree-styles")) return;
  const style = document.createElement("style");
  style.id = "xsec-conversation-tree-styles";
  style.textContent = STYLES;
  document.head.append(style);
}
