const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const rows=value=>Array.isArray(value)?value:Array.isArray(value?.items)?value.items:[];
const stamp=value=>Number.isFinite(Number(value))?new Date(Number(value)).toLocaleString("zh-CN"):"—";
const css=`:root{color:#d8dee9;background:#0f141b;font:13px/1.45 system-ui,sans-serif}*{box-sizing:border-box}body{margin:0}.app{padding:18px;min-height:100vh}.head,.toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px}.head h1{margin:0;font-size:20px}.muted,.status{color:#8d99aa}.toolbar{justify-content:flex-start;margin:16px 0;flex-wrap:wrap}button,input{border:1px solid #344052;border-radius:7px;background:#17202b;color:inherit;padding:7px 10px}button{cursor:pointer}.grid{display:grid;grid-template-columns:minmax(220px,32%) 1fr;gap:12px}.panel{border:1px solid #2c3746;border-radius:10px;background:#121a24;overflow:hidden}.panel h2{font-size:13px;margin:0;padding:11px 13px;border-bottom:1px solid #2c3746}.list{max-height:calc(100vh - 170px);overflow:auto}.row{display:block;width:100%;text-align:left;border:0;border-bottom:1px solid #27313f;border-radius:0;background:transparent;padding:10px 13px}.row:hover,.row.active{background:#1c2938}.row strong,.row span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.row small{color:#8d99aa}.badge{display:inline!important;color:#77d49b}.empty{padding:25px;color:#8d99aa;text-align:center}.status.error{color:#ff8d8d}@media(max-width:650px){.grid{grid-template-columns:1fr}.list{max-height:300px}}`;
export function activate(host){let root,runId="",query="",rev=0,c={};
 const status=(text,error=false)=>{c.status.textContent=text;c.status.className=`status${error?" error":""}`};
 const renderRuns=data=>{c.runs.replaceChildren();const items=rows(data);if(!items.length)c.runs.append(el("div","empty","暂无真实采集运行"));for(const r of items){const b=el("button",`row${runId===r.id?" active":""}`);b.type="button";b.append(el("strong","",r.name||r.id),el("small","",`${r.provider||"未知来源"} · ${r.status||"unknown"} · ${r.total??0} 项`),el("small","",stamp(r.updated_at)));b.onclick=()=>{runId=runId===r.id?"":r.id;void load()};c.runs.append(b)}};
 const renderAssets=data=>{c.assets.replaceChildren();const items=rows(data);if(!items.length)c.assets.append(el("div","empty","没有匹配的云端采集资产"));for(const a of items){const b=el("article","row");b.append(el("strong","",a.normalized_value||a.raw_value||a.id),el("small","",`${a.type||"asset"} · ${a.source_provider||"未知来源"}`),el("small",a.imported?"badge":"",a.imported?"已导入项目":"尚未导入"));c.assets.append(b)}};
 async function load(){const current=++rev;c.refresh.disabled=true;status("正在读取采集运行与资产…");try{const [runsData,assetsData]=await Promise.all([host.request("xsec.asset-discovery.runs.list",{}),host.request("xsec.asset-discovery.assets.list",{runId:runId||undefined,query:query||undefined,limit:300})]);if(current!==rev)return;renderRuns(runsData);renderAssets(assetsData);status(`已加载 ${rows(runsData).length} 个运行、${rows(assetsData).length} 项资产`)}catch(e){if(current===rev){renderRuns([]);renderAssets([]);status(`加载资产发现数据失败：${e instanceof Error?e.message:String(e)}`,true)}}finally{if(current===rev)c.refresh.disabled=false}}
 function build(){root.replaceChildren();root.append(el("style","",css));const app=el("main","app"),head=el("header","head"),title=el("div");title.append(el("h1","","资产发现"),el("div","muted","真实采集运行与已发现资产"));const refresh=el("button","","刷新");refresh.onclick=()=>void load();head.append(title,refresh);const toolbar=el("div","toolbar"),search=el("input");search.placeholder="按主机或资产值搜索";search.onchange=()=>{query=search.value.trim();void load()};toolbar.append(search);const statusNode=el("p","status"),grid=el("div","grid"),left=el("section","panel"),right=el("section","panel"),runsNode=el("div","list"),assetsNode=el("div","list");left.append(el("h2","","采集运行（点击筛选）"),runsNode);right.append(el("h2","","发现资产"),assetsNode);grid.append(left,right);app.append(head,toolbar,statusNode,grid);root.append(app);c={status:statusNode,refresh,runs:runsNode,assets:assetsNode};void load()}
 return{mount(nextRoot){root=nextRoot;build()},update(){},dispose(){rev++}}}
